---

- name: Deploy my application to all ubuntu webservers running in AWS
  hosts: webservers
  become: true

  tasks:
    - name: update ec2 instance
      apt:
        name: "*"
        state: latest

    - name: install the latest version of nginx
      apt:
        name: nginx
        state: latest

    - name: start nginx server, if not started
      service:
        name: nginx
        state: started

    - name: enable nginx server
      service:
        name: nginx
        enabled: yes

    - name: change directory to the html directory
      shell: cd /var/www/html

    - name: download application code from github
      get_url:
        url: https://github.com/azeezsalu/techmax/archive/refs/heads/main.zip
        dest: /var/www/html/

    - name: install unzip on the target server
      apt:
        name: unzip
        state: latest

    - name: unzip the zip folder
      unarchive:
        src: /var/www/html/techmax-main.zip
        dest: /var/www/html
        remote_src: yes

    - name: copy application code from the application directory to the html directory
      copy:
        src: /var/www/html/techmax-main/
        dest: /var/www/html
        remote_src: yes
      notify: Restart Application Service

    - name: remove the application directory
      file:
        path: /var/www/html/techmax-main
        state: absent

    - name: remove the application.zip folder
      file:
        path: /var/www/html/techmax-main.zip
        state: absent

  handlers:
    - name: Restart Application Service
      service:
        name: nginx
        state: restarted

