---

- name: Deploy my application to all ubuntu webservers running in AWS
  hosts: webservers
  become: true
  vars:
    base_path: /var/www/html  

  tasks:
    - name: update ec2 instance
      apt:
        name: "*"
        state: latest

    - name: install the latest version of nginx
      apt:
        name: nginx
        state: latest

    - name: start nginx server, if not started
      service:
        name: nginx
        state: started

    - name: enable nginx server
      service:
        name: nginx
        enabled: yes

    - name: change directory to the html directory
      shell: cd "{{base_path}}"

    - name: download application code from github
      get_url:
        url: https://github.com/Jul977/Ansible-project/archive/refs/heads/master.zip
        dest: "{{base_path}}/"

    - name: install unzip on the target server
      apt:
        name: unzip
        state: latest

    - name: unzip the zip folder
      unarchive:
        src: "{{base_path}}/Ansible-project-master.zip"
        dest: "{{base_path}}"
        remote_src: yes

    - name: copy application code from the application directory to the html directory
      copy:
        src: "{{base_path}}/Ansible-project-master/"
        dest: "{{base_path}}"
        remote_src: yes
      notify: Restart Application Service

    - name: remove the application directory
      file:
        path: "{{base_path}}/Ansible-project-master"
        state: absent

    - name: remove the application.zip folder
      file:
        path: "{{base_path}}/Ansible-project-master.zip"
        state: absent

  handlers:
    - name: Restart Application Service
      service:
        name: nginx
        state: restarted

